
# Introduction {-}

## Purpose{-}

The Horsefly River (Secwepemcúl’ecw) Watershed Connectivity Restoration Plan (WCRP) represents the culmination of a collaborative planning effort, which aims to improve connectivity for anadromous salmon and the livelihoods that they support, including the continued sustenance, cultural, and ceremonial needs of the Northern Secwépemc people and build collaborative partnerships within the Horsefly River watershed to achieve this goal. This 20-year plan was developed to identify priority actions that the Horsefly River WCRP Planning Team (see Appendix B – Partners and Detailed Methods)  will undertake between 2021-2040 to conserve and restore fish passage through barrier rehabilitation and  prevention strategies. 

WCRPs are long-term, actionable plans that blend local stakeholder and rightsholder knowledge with innovative geographic information systems (GIS) analyses to gain a shared understanding of where restoration efforts will have the greatest benefit for anadromous salmon. The planning process is inspired by the Conservation Standards (v.4.0), which is a conservation planning framework that allows planning teams to systematically identify, implement, and monitor strategies to apply the most effective solutions to high-priority conservation problems. There is a rich history of fish habitat planning and restoration work in the Horsefly River watershed that this WCRP builds upon, including work undertaken by the B.C. Fish Passage Technical Working Group, the Northern Secwepemc te Qelmucw (NStQ) and member communities, the Horsefly River Roundtable, and other local organizations (Masse 2018; S. Hocquard, Steve Hocquard Consulting, pers. comm.). 

Local data and knowledge are combined with connectivity modelling to estimate current connectivity status and identify structures that potentially block the most habitat. This informs the prioritization of field assessments to close the most significant knowledge gaps efficiently. Information from field assessments of barrier status and habitat condition are incorporated into the model, improving understanding of which barriers block the most habitat. 

This information is also used to inform and plan restoration efforts. Structure rankings inform restoration prioritization by summarizing what is known about fragmentation and showing the relative amount of habitat upstream of each barrier. Actual prioritization of restoration activities is a social decision that requires additional information, including the quality and condition of upstream habitat, the cultural importance of different areas within the watershed, and the costs and logistics of addressing each barrier relative to the ecological benefits of doing so.  

As knowledge gaps are closed and barriers are addressed, this plan is revised to summarize progress and provide updated estimates of connectivity status and the status and relative importance of remaining structures. 


## Vision Statement  {-}

Healthy, well-connected streams and rivers within the Horsefly River watershed support thriving populations of migratory fish, improving the overall ecosystem health of the watershed. In turn, these fish provide the continued sustenance, cultural, and ceremonial needs of the Northern Secwépemc People, as they have since time immemorial. Both residents and visitors to the watershed work together to mitigate the negative effects of human-made aquatic barriers, improving the resiliency of streams and rivers for the benefit and appreciation of all. 


## Scope  {-}

Connectivity influences critical components of freshwater ecosystem structure and function, such as aquatic species dispersal and migration, the transport of energy and matter (e.g., nutrient cycling and sediment flows), and temperature regulation (Seliger and Zeiringer (2018)). Though each of these factors are important when considering the health of a watershed, for the purposes of this WCRP the term “connectivity” is defined as the degree to which focal species can disperse or migrate freely through freshwater systems. Within this context, connectivity is primarily constrained by physical barriers, including human-made infrastructure such as dams, weirs, and stream crossings, and natural features such as waterfalls and debris flows. This plan is intended to focus on the direct rehabilitation and prevention of localized, physical barriers instead of the broad land-use patterns that are causing chronic connectivity issues in the watershed. The Planning Team decided that the primary focus of this WCRP is addressing barriers to both longitudinal connectivity (i.e., along the upstream-downstream plane) and lateral connectivity (i.e., connectivity between the mainstem and adjacent riparian wetlands and floodplains) due to the importance of maintaining fish passage to spawning, rearing, and overwintering habitat in the watershed. 

This WCRP focuses on habitat connectivity for Sockeye Salmon (Oncorhynchus nerka), Chinook Salmon (O. tschawytcha), and Coho Salmon (O. kisutch); herein referred to as Pacific salmon, in the Horsefly River watershed (Secwepemcúl’ecw), located in the upper Fraser River drainage basin in central British Columbia (Figure 3).  

The Horsefly River watershed has a drainage area of 276,603 ha, spanning from the Quesnel Highlands in the southeast to the confluence with Quesnel Lake in the northwest. There are two impassable waterfalls in the watershed that serve as complete barriers to fish passage: one on the mainstem Horsefly River approximately 4 km upstream of the confluence with McKinley Creek, and the second on Moffat Creek approximately 5 km upstream from where it flows into the Horsefly River. Culturally and economically important populations of Chinook Salmon, Coho Salmon, and Sockeye Salmon are all found in the watershed (Table 1), which historically supported Indigenous sustenance and trading economies (W. L. F. Nation. (2021), X. F. Nation. (2021)). The Horsefly River watershed comprises parts of Secwepemcúl’ecw, the traditional territory of the Northern Secwepemc te Qelmucw (NStQ), represented by the Northern Shuswap Tribal Council and four member communities or autonomous nations: 
- Xatśūll Cmetem’ (Soda Creek First Nations) 
- Stswēceḿc Xgāt’tem (Canoe Creek/Dog Creek First Nations) 
- T’ēxelc (Williams Lake First Nation) 
- Tsq’ēsceń (Canim Lake First Nation) 

Table 1: Focal fish species in the Horsefly River watershed. The Secwepemctsín and Western common and scientific species names are provided. 


## Focal Species {-}

### Anadromous Salmon {-}
Anadromous salmon are cultural and ecological keystone species that contribute to productive ecosystems by contributing marine-derived nutrients to the watershed and forming an important food source for other species. Salmon species are sacred to the NStQ, having sustained life, trading economies, and culture since time immemorial (W. L. F. Nation. 2021, X. F. Nation 2021, N. Singi pers. comm.). The stewardship of the resources and fisheries in their traditional territories are imbued in the spirit of the NStQ through a symbiotic relationship based on respect – the NStQ never take more salmon than are needed, and there is no waste. The entirety of the salmon is used - smoked and dried to sustain the NStQ through the winter months, the roe harvested for consumption, salmon oil rendered to be stored and traded, and the skin used to store the oil (Wilson, Twohig, and Dahlstrom 1998, X. F. Nation 2021, N. Singi pers. comm.). The salmon runs begin to return to the Horsefly River watershed in early August, and the NStQ traditionally celebrate and feast at this time. The harvest of the salmon strengthens the cultural connection to the land and the waters, providing an important food source for communities and the opportunity to pass knowledge and ceremony to future generations through fishing and fish processing (W. L. F. Nation2021, X. F. Nation 2021). 

Anadromous salmon populations in the Horsefly River watershed have declined significantly in the past few decades, with the populations of all three focal species being listed as Threatened or Endangered by the Committee on the Status of Endangered Wildlife in Canada. This has been exacerbated by the Big Bar landslide on the Fraser River in 2019 and the Chilcotin River landslide in 2024, leading the four NStQ communities to voluntarily close the salmon fishery from 2019 through 2024. The stewardship of their waters continues through the work of the NStQ member communities and the Northern Shuswap Tribal Council. 


### Chinook Salmon | Kekèsu | Oncorhynchus tshawytscha {-}
Table 2: Chinook Salmon population assessments in the Horsefly River watershed. Conservation Unit assessments (a) were undertaken by the Pacific Salmon Foundation (2025). Designated Unit assessments (b) were undertaken by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC 2018). 

Chinook Salmon are the first to return each year, usually in early August (DFO1991), and have the most limited distribution within the watershed. Known spawning occurs in parts of the Horsefly River mainstem above the confluence with the Little Horsefly River and throughout McKinley Creek as far upstream as Elbow Lake (DFO1991, S. Hocquard, pers. comm.). Important rearing systems include Patenaude Creek, Kroener Creek, Black Creek, Woodjam Creek, Deerhorn Creek, and Wilmot Creek (S. Hocquard, pers. comm.). 


### Coho Salmon | Sxeyqs | Oncorhynchus kisutch  {-}
Table 3: Coho Salmon population assessments in the Horsefly River watershed. Conservation Unit assessments (a) were undertaken by the Pacific Salmon Foundation (2025). Designated Unit assessments (b) were undertaken by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC 2016). 

Coho Salmon are the most widely distributed of the three focal species in the watershed, with the ability to migrate into smaller, upper tributary systems (DFO 1991). Spawning occurs in the Little Horsefly River between Gruhs Lake and Horsefly Lake, McKinley Creek below McKinley Lake, Woodjam Creek, Patenaude Creek, Tisdall Creek, and Black Creek. Rearing fry and juveniles have been observed in the Little Horsefly River, Patenaude Creek, and McKinley Creek up to Bosk Lake (DFO 1991, S. Hocquard pers. comm.). 


### Sockeye Salmon | Sqlelten7ùwi | Oncorhynchus nerka  {-}
Table 4: Sockeye Salmon population assessments in the Horsefly River watershed. Conservation Unit assessments were undertaken by the Pacific Salmon Foundation (2025). Designated Unit assessments (b) were undertaken by the Committee on the Status of Endangered Wildlife in Canada (COSEWIC 2017). 

Sockeye Salmon have historically been the most abundant of the three focal species in the watershed, though the population has seen significant declines in recent years (DFO 1991, S. Hocquard pers. comm.). Sockeye Salmon spawning is known to occur throughout the Horsefly River (up to the impassable falls), in the Little Horsefly River between Gruhs Lake and Horsefly Lake, Moffat Creek (up to the impassable falls), and McKinley Creek up to Elbow Lake (Pacific-Salmon-Foundation 2020, DFO 1991, S. Hocquard pers. comm.). Additionally, a spawning channel aimed at enhancing the Sockeye Salmon population was constructed by Fisheries and Oceans Canada in 1989 (DFO 1991). Currently, there are no known Sockeye Salmon rearing habitats in the Horsefly River watershed – all emergent fry migrate down to Quesnel Lake. 


## Barrier Types {-}

The following table highlights which barrier types were believed to pose the greatest threat to anadromous salmon in the watershed by the Planning Team prior to field verification. The results of this assessment were used to inform the subsequent planning steps and to identify knowledge gaps where there is little spatial data to inform the assessment for a specific barrier type. 

Table 5: Structure types in the Horsefly River watershed and barrier rating assessment results prior to field verification. For each structure type listed, Extent refers to the proportion of focal species habitat that is being blocked by that structure type, Severity is the proportion of structures for each structure type that are known to block passage for focal species based on field assessments, and Irreversibility is the degree to which the effects of a structure type can be reversed and connectivity restored.  


## Road-stream Crossings {-}

Road-stream crossings are the most abundant structure type in the watershed and include a combination of demographic road crossings (highways, municipal, and paved roads) and resource roads. The Planning Team felt that the overall threat rating underestimated the severity of road-stream crossing structures in the watershed, and therefore decided to update the overall threat rating from High to Very High. The Planning Team also felt that an irreversibility rating of Medium was appropriate due to the technical complexity and resources required to rehabilitate road-stream crossings. 


## Lateral Barriers {-}

There are numerous types of lateral barriers that potentially occur in the watershed, including dykes, berms, and linear development (i.e., road and rail lines), all of which can restrict the ability of anadromous salmon to move into floodplains, riparian wetlands, and other off-channel habitats. No comprehensive lateral barrier data exists within the watershed, so pressure ratings were based on qualitative local knowledge. Lateral barriers are not thought to be as prevalent as road- or rail-stream crossings but are likely very severe where they do exist. Significant lateral barriers are known to occur along the mainstem of the Horsefly River, which disconnect the mainstem river from historic floodplain and off-channel habitat. Overall, the Planning Team decided that a High pressure rating adequately captured the effect that lateral barriers are having on connectivity in the watershed.  


## Small Dams (<3 m height) {-}

There were 6 mapped small dams prior to field verification that could affect passage for anadromous salmonids in the watershed, resulting in a medium extent. There are two known fish-passage structures in the watershed, including on the dam at the outlet of McKinley Lake. Dams that block passage for anadromous salmon and would require significant resources to rehabilitate. However, due to the limited extent of dams in the watershed, a final pressure rating of Medium was assigned. 


## Trail-stream Crossings {-}

There is very little spatial data available on trail-stream crossings in the watershed, so the Planning Team was unable to quantify the true Extent and Severity of this structure type. However, the Planning Team felt that trail-stream crossings are not prevalent within the watershed and that, where they do exist, they do not significantly impact restrict passage for anadromous salmon. As most crossings will be fords or similar structures, rehabilitation may not be required, or rehabilitation costs associated with these structures would be quite low. Overall, the Planning Team felt that the pressure rating for trail-stream crossings was likely Low; however, the lack of ground-truthed evidence to support this rating was identified as a knowledge gap within this plan. 

## Natural Barriers {-}

Natural barriers to fish passage can include debris flows, log jams, and sediment deposits, etc., but natural features that have always restricted fish passage (e.g., waterfalls) are not considered under this barrier type. Natural barriers are difficult to include in a spatial prioritization framework due to their transient nature. The Planning Team identified known natural barriers that occur throughout the watershed, such as beaver dams and log jams. Generally, these natural barriers are only severe impediments to fish passage during low-flow years, but reduced baseflows have become more common in recent years. Based on this, the Planning Team felt that natural barriers will be severe most years where they exist, but are mostly reversible, resulting in an overall pressure rating of Low. 
