
# Acknowledgements and References {-}

## Recommended Citation 

B. Rebellato, N. Mazany-Wright, F. Montgomery, S. Sra, and N. W. R. Lapointe. 2026. Horsefly River Watershed Secwepemcúl’ecw Connectivity Restoration Plan: 2021 - 2040. Canadian Wildlife Federation. Ottawa, Ontario, Canada. 


## Acknowledgements {-}

This plan represents a collaborative planning process undertaken in the Horsefly River watershed with a multi-partner planning team of individuals and groups passionate about the conservation and restoration of freshwater ecosystems and the species they support. Plan development was funded by the B.C. Salmon Restoration and Innovation Fund, Canada Nature Fund for Aquatic Species at Risk, and the RBC Bluewater Project. We were fortunate to benefit from the feedback, guidance, and wisdom of many groups and individuals who volunteered their time throughout this process — this publication would not have been possible without the engagement of our partners and the Planning Team (see Planning Team in Appendix B – Partners and Detailed Methods). 

We recognize the incredible fish passage and connectivity work that has occurred in the Horsefly River watershed to date, and we are excited to continue partnering with local groups and organizations to build upon existing initiatives and provide a road map to push connectivity work forward over the next 20 years and beyond. 

The Canadian Wildlife Federation recognizes that the lands and waters that form the basis of this plan are the traditional unceded territory of the Northern Secwepemc people. We are grateful for the opportunity to learn from the stewards of this land and work together to benefit Pacific salmon. A special thank you to Nishitha Singi for sharing the traditional Secwepemctsín names used in this plan. 

Model outputs were refined based on feedback provided by local knowledge holders beyond the Planning Team. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.  


## References {-}

Agrawal, A., R. S. Schick, E. P. Bjorkstedt, R. G. Szerlong, M. N. Goslin, B. C. Spence, T. H. Williams, and K. M. Burnett. 2005. Predicting the potential for historical Coho, Chinook, and Steelhead habitat in northern California. National Oceanic and Atmospheric Administration, NOAA-TM-NMFS-SWFSC-379.  

Bjornn, T. C., and D. W. Reiser. 1991. Habitat requirements of salmonids in streams. In Influences of Forest and Rangeland Management on Salmonid Fishes and their Habitats. American Fisheries Society Special Publication 19: 83-138.  

Burnett, K. M., G. H. Reeves, D. J. Miller, S. Clarke, K. Vance-Borland, K. Christiansen. 2007. Distribution of salmon-habitat potential relative to landscape characteristics and implications for conservation. Ecological Applications 17: 66-80.  

Busch, D. S., M. Sheer, K. Burnett, P. McElhany, and T. Cooney. 2011. Landscape-level model to predict spawning habitat for lower Columbia River fall Chinook Salmon (Oncorhynchus tshawytscha). River Research Applications 29: 291-312.  

Cooney, T., and D. Holzer. 2006. Appendix C: Interior Columbia basin stream type Chinook Salmon and Steelhead populations: habitat intrinsic potential analysis. National Oceanic and Atmospheric Administration, Northwest Fisheries Center.  

COSEWIC. 2016. COSEWIC Assessment and Status Report on the Coho Salmon Oncorhynchus kisutch, Interior Fraser Population, in Canada. Committee on the Status of Endangered Wildlife in Canada, Ottawa, Ontario. https://www.canada.ca/en/environment-climate-change/services/species-risk-public-registry/cosewic-assessments-status-reports/coho-salmon-interior-fraser-2016.html.  

COSEWIC. 2017. COSEWIC Assessment and Status Report on the Sockeye Salmon Oncorhynchus nerka, 24 Designatable Units in the Fraser River Drainage Basin, in Canada. Committee on the Status of Endangered Wildlife in Canada, Ottawa, Ontario. https://www.sararegistry.gc.ca/virtual_sara/files/cosewic/srSockeyeSalmon2017e.pdf.  

COSEWIC. 2018. COSEWIC Assessment and Status Report on the Chinook Salmon Oncorhynchus tshawytscha, Designatable Units in Southern British Columbia (Part One – Designatable Units with no or low levels of artificial releases in the last 12 years), in Canada. Committee on the Status of Endangered Wildlife in Canada, Ottawa, Ontario. https://www.canada.ca/en/environment-climate-change/services/species-risk-public-registry/cosewic-assessments-status-reports/chinook-salmon-2018/document-info-summaries.html.  

[DFO] Fisheries and Ocean Canada. 1991. Fish habitat inventory and information program - stream summary information.  

Lake, R. G. 1999. Activity and spawning behaviour in spawning Sockeye salmon. Thesis, University of British Columbia. 

Masse Environmental Consultants Ltd. 2018. Fish Habitat Confirmation Assessments Horsefly River Watershed. Prepared for Ministry of Environment & Climate Change Strategy.  

Mazany-Wright, N., S. M. Norris, N. W. R. Lapointe, and B. Rebellato. 2021a. A Freshwater Connectivity Modelling Framework to Support Barrier Prioritization and Remediation in British Columbia. Canadian Wildlife Federation, Ottawa, Ontario.  

Mazany-Wright, N., S. M. Norris, N. W. R. Lapointe, and B. Rebellato. 2021b. B.C. Fish Passage Restoration Initiative Target Watershed Selection Process: Technical Documentation. Canadian Wildlife Federation, Ottawa, Ontario.  

Mazany-Wright, N., J. Noseworthy, S. Sra, S. M. Norris, and N. W. R Lapointe. 2021c. Breaking Down Barriers: a Practitioners' Guide to Watershed Connectivity Remediation Planning. Canadian Wildlife Federation, Ottawa, Ontario.  

McMahon, T. E. 1983. Habitat suitability index models: coho salmon. U.S. Department of the Interior, Fish and Wildlife Service. FWS/OBS-82/10.49. 29 pp.  

Neuman H. R., and C. P. Newcombe. 1977. Minimum acceptable stream flows in British Columbia: a review. Fisheries Management Report No. 70.  

[NStQ] Northern Secwepemc to Qelmucw. 2019. Saving the Salmon. Lexéy’em – Fall 2019. https://nstq.ca/wp-content/uploads/2019/09/Lexeyem_Fall-2019_Final.pdf.  

Pacific Salmon Foundation. 2025. Methods for Assessing Status and Trends in Pacific Salmon Conservation Units and their Freshwater Habitats. The Pacific Salmon Foundation, Vancouver BC, Canada. Version 13. Available at https://salmonwatersheds.ca/document/lib_475/ 

Porter, M., D. Pickard, K. Wieckowski, and K. Bryan. 2008. Developing Fish Habitat Models for Broad-Scale Forest Planning in the Southern Interior of B.C. ESSA Technologies Ltd. and B.C. Ministry of Environment.  

Raleigh, R. F., and W. J. Miller. 1986. Habitat suitability index models and instream flow suitability curves: chinook salmon. U.S. Fish and Wildlife Service Biological Reports 82. 64pp.  

Roberge, M., J. B. M. Hume, C. K. Minns, and T. Slaney. 2002. Life history characteristics of freshwater fishes occurring in British Columbia and the Yukon, with major emphasis on stream habitat characteristics. Fisheries and Oceans Canada, Marine Environment and Habitat Science Division, Cultus Lake, British Columbia.  

Rosenfeld, J., M. Porter, and E. Parkinson. 2000. Habitat factors affecting the abundance and distribution of juvenile cutthroat trout (Oncorhynchus clarki) and coho salmon (Oncorhynchus kisutch). Canadian Journal of Fisheries and Aquatic Sciences 57: 766-774.  

Seliger, Carina, and Bernhard Zeiringer. 2018. River Connectivity, Habitat Fragmentation and Related Restoration Measures. In Riverine Ecosystem Management: Science for Governing Towards a Sustainable Future, edited by Stefan Schmutz and Jan Sendzimir, 171–86. Cham: Springer International Publishing. https://doi.org/10.1007/978-3-319-73250-3_9.  

Sheer, M. B., D. S. Busch, E. Gilbert, J. M. Bayer, S. Lanigan, J. L. Schei, K. M. Burnett, and D. Miller. 2009. Development and management of fish intrinsic potential data and methodologies: State of the IP 2008 summary report. Pacific Northwest Aquatic Monitoring Partnership Series 2009—4, 56 pp.  

Sheer, M. B., and E. A. Steel. 2006. Lost watersheds: barriers, aquatic habitat connectivity, and salmon persistence in the Willamette and Lower Columbia basins. Transactions of the American Fisheries Society 135: 1654-1669.  

Sloat M. R., G. H. Reeves, and K. R. Christiansen. Stream network geomorphology mediates predicted vulnerability of anadromous fish habitat fish habitat to hydrologic change in southeast Alaska.  

Williams Lake First Nation. 2021. Secwepemc Land Use Patterns. https://www.wlfn.ca/about-wlfn/history/.  

Wilson, I. R., K. Twohig, and B. Dahlstrom. 1998. Archaeological Overview Assessment Northern Secwepemc Traditional Territory. https://www2.gov.bc.ca/assets/gov/farming-natural-resources-and-industry/natural-resource-use/archaeology/forms-publications/aoa_-_williams_lake_-_northern_secwepemc_traditional_territory_-_1998_report.pdf.  

Woll, C., D. Albert, and D. Whited. 2017. A Preliminary Classification and Mapping of Salmon Ecological Systems in the Nushagak and Kvichak Watersheds, Alaska. The Nature Conservancy.  

Xatśūll First Nation. 2021. Traditional History. https://xatsull.com/history/. 

